/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Submission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'organization' : IDL.Text,
  'phone' : IDL.Text,
  'eventType' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteSubmission' : IDL.Func([IDL.Nat], [], []),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], []),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Submission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'organization' : IDL.Text,
    'phone' : IDL.Text,
    'eventType' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteSubmission' : IDL.Func([IDL.Nat], [], []),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], []),
    'submitBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };